Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -1,4 +1,5 @@
-name: Shaft_Api
+
+name: Shaft Api Tests
 
 on:
   workflow_dispatch:
@@ -10,8 +11,6 @@ on:
 jobs:
   E2E_Chrome_Linux_Test:
     runs-on: ubuntu-latest
-    permissions:
-      checks: write
     steps:
       - name: Checkout Code
         uses: actions/checkout@v4
@@ -19,7 +18,7 @@ jobs:
       - name: Setup JDK 21
         uses: actions/setup-java@v4
         with:
-          distribution: 'zulu'
+          distribution: 'zulu' # See 'Supported distributions' for available options
           java-version: '21'
       
       - name: Set up Maven
@@ -29,33 +28,25 @@ jobs:
 
       - name: Run Tests
         continue-on-error: true
-        run: mvn test -DbrowserType="chrome" -DheadlessExecution="true"  -Dtest="src/test/java/BookingApiTest.java"
+        run: mvn test -DbrowserType="chrome" -DheadlessExecution="true"  -Dtest="${{ github.event.inputs.testsPath }}"
 
-      - name: Generate Allure Report Single File
-        continue-on-error: true
-        run: |
-          sudo chmod -R a+rwx .allure/allure-2.25.0/bin
-          ./.allure/allure-2.25.0/bin/allure generate --single-file --clean target/allure-results
-    
-      - name: Upload Allure Report as Artifact
-        uses: actions/upload-artifact@v3
-        with:
-          name: Chrome_Linux_Allure
-          path: allure-report/index.html
-      
-      - name: Publish Report
-        continue-on-error: true
-        uses: dorny/test-reporter@v1
-        if: success() || failure()
-        with:
-          name: Tests Report Chrome_Linux
-          path: 'target/surefire-reports/TEST-*.xml'
-          reporter: java-junit
+      # - name: Publish Report
+      #   uses: dorny/test-reporter@v1
+      #   if: success() || failure()    # run this step even if previous step failed
+      #   with:
+      #     name: Tests Report            # Name of the check run which will be created
+      #     path: 'target/surefire-reports/TEST-*.xml'    # Path to test results
+      #     reporter: java-junit
+
+      # - name: Publish Test Results
+      #   uses: EnricoMi/publish-unit-test-result-action@v2
+      #   if: always()
+      #   with:
+      #     files: |
+      #       target/surefire-reports/TEST-*.xml
 
   E2E_Firefox_Windows_Test:
     runs-on: windows-latest
-    permissions:
-      checks: write
     steps:
       - name: Checkout Code
         uses: actions/checkout@v4
@@ -63,7 +54,7 @@ jobs:
       - name: Setup JDK 21
         uses: actions/setup-java@v4
         with:
-          distribution: 'zulu'
+          distribution: 'zulu' # See 'Supported distributions' for available options
           java-version: '21'
       
       - name: Set up Maven
@@ -73,23 +64,4 @@ jobs:
 
       - name: Run Tests
         continue-on-error: true
-        run: mvn test -DbrowserType="firefox" -DheadlessExecution="false"  -Dtest="src/test/java/BookingApiTest.java"
-
-      - name: Generate Allure Report Single File
-        continue-on-error: true
-        run: ./.allure/allure-2.25.0/bin/allure generate --single-file --clean target/allure-results
-    
-      - name: Upload Allure Report as Artifact
-        uses: actions/upload-artifact@v3
-        with:
-          name: Firefox_Windows_Allure
-          path: allure-report/index.html
-
-      - name: Publish Report 
-        continue-on-error: true
-        uses: dorny/test-reporter@v1
-        if: success() || failure()
-        with:
-          name: Tests Report Firefox_Windows
-          path: 'target/surefire-reports/TEST-*.xml'
-          reporter: java-junit
+        run: mvn test -DbrowserType="firefox" -DheadlessExecution="true"  -Dtest="${{ github.event.inputs.testsPath }}"
